# Generated by Django 5.0.7 on 2024-09-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0002_worksession_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='pause_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksession',
            name='paused',
            field=models.BooleanField(default=False),
        ),
    ]
