# Generated by Django 5.0.7 on 2024-09-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0003_worksession_pause_time_worksession_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='machine',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
