# Generated by Django 5.0.7 on 2024-09-12 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0004_worksession_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksession',
            name='machine',
        ),
    ]
