# Generated by Django 5.0.7 on 2024-09-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0005_remove_worksession_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='machine',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
