# Generated by Django 5.0.7 on 2024-09-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0008_worksession_confirmed_worksession_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
    ]
